# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentserver" do
  version "0.30.4"

  on_macos do
    on_intel do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-darwin-amd64.tar.gz"
      sha256 "55a7427bb64af87e54b47d9ab1b2cecaa1459a2532121a2402583ba4f60c5946"
    end
    on_arm do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-darwin-arm64.tar.gz"
      sha256 "b10a4ce762d983cc15389c41b93d696280d374c15bf084087389a3b7de32b0f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-linux-amd64.tar.gz"
      sha256 "06da87410abb1b90dccd9d37ea9e7a261bc55ff57d18b0e83f91145dcb72a142"
    end
    on_arm do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-linux-arm64.tar.gz"
      sha256 "3feaebc2000ba2579a7751013564bfb7fe2a69d61887cc344a5a5f3f22088004"
    end
  end

  name "agentserver"
  desc "Connect local opencode to agentserver via WebSocket tunnel"
  homepage "https://github.com/agentserver/agentserver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentserver"

  # No zap stanza required

end
