# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentserver" do
  version "0.35.0"

  on_macos do
    on_intel do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-darwin-amd64.tar.gz"
      sha256 "07dd46afe8a4784aa2e3402e9637bc1f24708f5127293088d2c057ae16e83ab0"
    end
    on_arm do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-darwin-arm64.tar.gz"
      sha256 "ad967fa395084b9fc6a09350348b66ed85b222473ddd9aa38bb59a28c7836d49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-linux-amd64.tar.gz"
      sha256 "2807a60589c2104539ac1b0885546cda1275bde82ef26a8d6946d6aee3d70bb0"
    end
    on_arm do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-linux-arm64.tar.gz"
      sha256 "2a9a70f822607d4c7a6590e750e0034415c7b989899c6850b7b622a3e734056d"
    end
  end

  name "agentserver"
  desc "Connect local opencode to agentserver via WebSocket tunnel"
  homepage "https://github.com/agentserver/agentserver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentserver"

  # No zap stanza required

end
