# This file was generated by GoReleaser. DO NOT EDIT.
cask "agentserver" do
  version "0.35.3"

  on_macos do
    on_intel do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-darwin-amd64.tar.gz"
      sha256 "b1aa03440ee241e1354750cd72bc69eba97bfaf50e3638d3b4f2cc846d7fff36"
    end
    on_arm do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-darwin-arm64.tar.gz"
      sha256 "d059c068796711985d5b83400b9feb1334e9ad1c36925011120ad230d785af63"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-linux-amd64.tar.gz"
      sha256 "e21350b07bd190c0200e9367013f049cbd429f8f48c277c1ccba07721c180f60"
    end
    on_arm do
      url "https://github.com/agentserver/agentserver/releases/download/v#{version}/agentserver-linux-arm64.tar.gz"
      sha256 "a503d751b9b5b29400eb7412f05a572cad21ab0c981366297c246d5314ae8a96"
    end
  end

  name "agentserver"
  desc "Connect local opencode to agentserver via WebSocket tunnel"
  homepage "https://github.com/agentserver/agentserver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "agentserver"

  # No zap stanza required

end
